services:
  mongodb:
    image: mongo:latest
    container_name: proj2425_sparks4future_mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=request
      - MONGO_INITDB_ROOT_PASSWORD=Zu2oo02jknAl2jnkls
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    networks:
      - proj2425_sparks4future

  nodejs:
    build:
      context: ./data/src
      dockerfile: Dockerfile
    container_name: proj2425_sparks4future_nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    ports:
      - 63000:3000
    depends_on:
      - mongodb
    networks:
      - proj2425_sparks4future

networks:
  proj2425_sparks4future:
    name: proj2425_sparks4future